language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
  - $HOME/.cache/yarn
  - .next/cache
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: main